### ISSUE TITLE
Different Cart Item Modal Bug (see description) 

### ISSUE THREAD

**Issue by ASharfi13** [ASharfi13/Group-UberEats-Clone#16]
If a User signs out while items were in his cart and the Un-registered/Not-logged-in User attempts to add a menu-item to his cart - this triggers the Different Cart Item Modal to trigger when nothing is in the cart.

**Comment by jiangroyce** [comment]
happens because logging out only sets cart items to [], not restaurant name or anything else.
Added Clear Cart function to cart context and refactored all to use this function
